CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text,
  email text UNIQUE,
  profile_image_path text,
  created_at timestamptz NOT NULL DEFAULT now(),
  password_hash text,
  google_sub text,
  email_verified boolean NOT NULL DEFAULT false,
  last_login_at timestamptz,
  is_active boolean NOT NULL DEFAULT true,
  auth_provider varchar NOT NULL DEFAULT 'local'
);

CREATE TABLE public.sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  created_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  user_id bigint,
  session_id varchar NOT NULL UNIQUE,
  ip_address varchar,
  user_agent varchar,
  last_accessed_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sessions_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public.users(id)
    ON DELETE SET NULL
);

CREATE TABLE public.chats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id bigint NOT NULL,
  session_id bigint,
  CONSTRAINT chats_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES public.users(id)
    ON DELETE CASCADE,
  CONSTRAINT chats_session_id_fkey
    FOREIGN KEY (session_id) REFERENCES public.sessions(id)
    ON DELETE SET NULL
);

CREATE TABLE public.customize (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL UNIQUE,
  custom_text varchar NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_customize_user
    FOREIGN KEY (user_id) REFERENCES public.users(id)
    ON DELETE CASCADE
);

CREATE TABLE public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content text NOT NULL,
  tool_tag text,
  created_at timestamptz NOT NULL DEFAULT now(),
  sender_id bigint,
  chat_id bigint NOT NULL,
  CONSTRAINT messages_chat_id_fkey
    FOREIGN KEY (chat_id) REFERENCES public.chats(id)
    ON DELETE CASCADE,
  CONSTRAINT messages_sender_id_fkey
    FOREIGN KEY (sender_id) REFERENCES public.users(id)
    ON DELETE SET NULL
);

CREATE TABLE public.chat_summaries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  summary_text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  chat_id bigint NOT NULL,
  CONSTRAINT fk_chat_summary_chat
    FOREIGN KEY (chat_id) REFERENCES public.chats(id)
    ON DELETE CASCADE
);

CREATE TABLE public.chat_quizzes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  chat_id bigint NOT NULL,
  CONSTRAINT fk_chat_quiz_chat
    FOREIGN KEY (chat_id) REFERENCES public.chats(id)
    ON DELETE CASCADE
);

CREATE INDEX idx_sessions_user_id ON public.sessions(user_id);
CREATE INDEX idx_chats_user_id ON public.chats(user_id);
CREATE INDEX idx_chats_session_id ON public.chats(session_id);
CREATE INDEX idx_messages_chat_id ON public.messages(chat_id);
CREATE INDEX idx_messages_sender_id ON public.messages(sender_id);
CREATE INDEX idx_chat_summaries_chat_id ON public.chat_summaries(chat_id);
CREATE INDEX idx_chat_quizzes_chat_id ON public.chat_quizzes(chat_id);
